name: Build
on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: postgres
          POSTGRES_DB: securetary
        options: >-
          --health-cmd pg_isready   
          --health-interval 10s 
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --configuration Release --filter "FullyQualifiedName!~AcceptanceTests"
      env:
        ConnectionStrings__DefaultConnection: Server=localhost;Port=5432;Database=postgres;User Id=postgres;Password=postgres;